export const subjectsByYear = {
    1: [
      "Fundamentos de Desarrollo Web",
      "Introducción a la Programación I",
      "Laboratorios de Redes y Sistemas Operativos",
      "Lógica y Matemática Discreta",
      "Pensamiento Creativo",
      "Álgebra",
      "Arquitectura de Ordenadores",
      "Introducción a la Programación II",
      "Laboratorio de Bases de Datos y Sistemas Distribuidos",
      "Sociedad Digital",
      "Proyectos I: Técnicas y Tecnologías Digitales",
    ],
    2: [
      "Fundamentos de Composición Visual",
      "Probabilidad y Estadística",
      "Programación Orientada a Objetos",
      "Redes de Ordenadores",
      "Sistemas Operativos",
      "Análisis y Diseño de Algoritmos",
      "Bases de Datos",
      "Cálculo",
      "Diseño de Software",
      "Negocios y Modelos Digitales",
      "Proyectos II: Tendencias de la Ingeniería del Software",
    ],
    3: [
      "Inteligencia Artificial",
      "Dirección y Gestión de Proyectos",
      "Programación de Sistemas Distribuidos",
      "Programación Web I, Cliente",
      "Programación Web II, Servidor",
      "Desarrollo de aplicaciones móviles",
      "Fundamentos de UX",
      "Proyectos III: Desarrollo Web y Apps",
      "Ampliación de Bases de Datos",
      "Búsqueda y Análisis de la Información",
      "Procesamiento de Datos",
    ],
    4: [
      "TFG",
      "Creación y Dirección de Empresas",
      "Ingeniería del Software",
      "Paradigmas de Programación",
      "Formación para el Empleo",
      "Prácticas en Empresa",
      "Programación de Bajo Nivel",
      "Verificación de Software",
      "Proyectos de Ingeniería de Datos",
      "Aprendizaje Automático I",
      "Visión por Computador",
      "Aprendizaje Automático II",
      "Visualización de Datos",
    ],
  };
  